#!/bin/sh
# build project with esbuild

ECHO=""; if test "$1" = "--dry-run"; then ECHO="echo"; fi
#MIN="--minify"; if test "$1" = "--dev"; then MIN=""; fi
#MIN="--minify --keep-names"; if test "$1" = "--dev"; then MIN=""; fi
MIN="--minify-whitespace --minify-syntax"; if test "$1" = "--dev"; then MIN=""; fi
BIN="/home/niko/bin/esbuild/node_modules/.bin/esbuild"
OPT="--bundle --target=es2017"
IN="."
OUT="build"

check() {
    test ! -f "$1" && echo "$1 missing" && exit 1
}
build() {
    $ECHO $BIN $OPT $MIN --outfile=$OUT/"$1" $IN/"$1"
}

check $BIN
build "index.js"
build "index.css"
